### ISSUE TITLE
Add your GitHub profile in CONTRIBUTOR.md

### ISSUE THREAD

**Issue by tarunjain1st** [tarunjain1st/Hacktoberfest2020#1]
Kindly check the README.md for basic syntax
when you add your information do place your blocks at the end of last statement.

**Comment by Justinnn07** [comment]
Sir, May i Do this!! 😀

**Comment by tarunjain1st** [comment]
@Justinnn07 everyone is free to do this

**Comment by Justinnn07** [comment]
> @Justinnn07 everyone is free to do this

thanks sir!

**Comment by sreyareddy15** [comment]
#19 details added, please merge

**Comment by adi44** [comment]
Hello I would like to do this issue

**Comment by tarunjain1st** [comment]
Yes sure @adi44 go ahead

**Comment by tanishq67** [comment]
Sir, can i do it ?

**Comment by tarunjain1st** [comment]
yes @tanishq67  go ahead
